- name: "Install Powerline for pleasant commandline operation"
  ansible.builtin.dnf:
    name: "{{ powerline }}"
    state: present

- name: edit .bashrc to enable powerline usage
  blockinfile:
    path: /home/{{ ansible_user }}/.bashrc
    block: |
      if [ -f `which powerline-daemon` ]; then
        powerline-daemon -q
        POWERLINE_BASH_CONTINUATION=1
        POWERLINE_BASH_SELECT=1
        . /usr/share/powerline/bash/powerline.sh
      fi
