---
# handlers file for server_common
  - name: "start fail2ban service"
    ansible.builtin.service:
      name: fail2ban
      state: started
      enabled: yes

  - name: qemu-guest-agent
    ansible.builtin.service:
      name: qemu-guest-agent
      state: started
      enabled: yes

  - name: dnf-automatic-timer
    ansible.builtin.systemd:
      name: dnf-automatic.timer
      state: restarted