---
# defaults file for server_common
ansible_python_interpreter: /usr/bin/python3

default:
  - nano
  - fail2ban
  - zstd
  - 'dnf-automatic'
  
monitor:
  - htop
  - sysstat
  - iotop
  - dmidecode
  - hyperfine

selinux:
  - libselinux-python3
  - policycoreutils-python-utils

powerline:
  - powerline
  - powerline-fonts
